---

master:
  hosts:
    example_service:
      ansible_become: yes
      ansibe_become_user: root
      ansible_become_password: example
      ansible_host: 10.0.0.23
      ansible_connection: ssh
      ansible_port: 22
      ansible_user: example
      ansible_password: example